name: Deploy Backend

on:
  push:
    branches: [ prod ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Push to medusa
      env:
        SSHKEY: ${{ secrets.MEDUSA_GLOBAL_DEPLOY_KEY }}
      run: |
        echo "$SSHKEY" > sshkey
        chmod 400 sshkey
        export GIT_SSH_COMMAND="ssh -i sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git push dokku@medusa.datasektionen.se:meta-tv2-backend $(git subtree -P Backend/Meta-TV2-api/ split):master --force
